[build-system]
requires = ["setuptools>=61.2"]
build-backend = "setuptools.build_meta"

[project]
name = "binsync"
classifiers = [
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
]
license = {text = "BSD 2 Clause"}
description = "A Collaboration framework for binary analysis tasks."
urls = {Homepage = "https://github.com/angr/binsync"}
requires-python = ">= 3.7"
dependencies = [
    "sortedcontainers",
    "toml",
    "GitPython",
    "filelock",
    "pycparser",
    "prompt_toolkit",
    "tqdm",
]
dynamic = ["version"]

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.optional-dependencies]
test = [
    "angr-management",
    "pytest-qt",
    "flake8",
    "pytest",
]
ghidra = [
    "ghidra_bridge",
    "PySide6-Essentials>=6.4.2",
]
extras = ["dailalib"]

[project.scripts]
binsync = "binsync.__main__:main"

[tool.setuptools]
include-package-data = true
license-files = ["LICENSE"]

[tool.setuptools.packages]
find = {namespaces = false}

[tool.setuptools.dynamic]
version = {attr = "binsync.__version__"}
